version: "2"
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - funlen
    - mnd
    - paralleltest
    - testpackage
    - wsl
  settings:
    lll:
      line-length: 120
    nlreturn:
      block-size: 3
  exclusions:
    generated: lax
    rules:
      - linters:
          - revive
        text: should not use dot imports
        source: ginkgo|gomega
      - linters:
          - goconst
        path: _test\.go
      - linters:
          - lll
        source: //\s*\+
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/cloudnative-pg/cnpg-i-machinery)
        - blank
        - dot
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
