version: '3'

tasks:
  spellcheck:
    desc: Run spellcheck
    env:
      # renovate: datasource=git-refs depName=spellcheck lookupName=https://github.com/cloudnative-pg/daggerverse currentValue=main
      DAGGER_SPELLCHECK_SHA: 00cead9710f409ceb3a818fe5fd7ba683ee93ac8
    cmds:
      - >
        GITHUB_REF= dagger -s call -m github.com/cloudnative-pg/daggerverse/spellcheck@${DAGGER_SPELLCHECK_SHA}
        spellcheck --source . stdout
    sources:
      - ./**

  lint:
    desc: Run golangci-lint
    env:
      # renovate: datasource=git-refs depName=golangci-lint lookupName=https://github.com/sagikazarmark/daggerverse currentValue=main
      DAGGER_GOLANGCI_LINT_SHA: e6c14178bcaaff9e102e2a89173ca31479b80629
    cmds:
      - >
        GITHUB_REF= dagger -s call -m github.com/sagikazarmark/daggerverse/golangci-lint@${DAGGER_GOLANGCI_LINT_SHA}
        run --source . --config .golangci.yml stdout
    sources:
      - ./**/*.go
      - .golangci.yml

  commitlint:
    desc: Check for conventional commits
    env:
      # renovate: datasource=git-refs depName=commitlint lookupName=https://github.com/cloudnative-pg/daggerverse currentValue=main
      DAGGER_COMMITLINT_SHA: 00cead9710f409ceb3a818fe5fd7ba683ee93ac8
    cmds:
      - GITHUB_REF= dagger -s call -m github.com/cloudnative-pg/daggerverse/commitlint@${DAGGER_COMMITLINT_SHA} lint --source . --args "--from=origin/main" stdout

  uncommitted:
    desc: Check for uncommitted changes
    env:
      # renovate: datasource=git-refs depName=uncommitted lookupName=https://github.com/cloudnative-pg/daggerverse currentValue=main
      DAGGER_UNCOMMITTED_SHA: 00cead9710f409ceb3a818fe5fd7ba683ee93ac8
    cmds:
      - >
        GITHUB_REF= dagger -s call -m github.com/cloudnative-pg/daggerverse/uncommitted@${DAGGER_UNCOMMITTED_SHA}
        check-uncommitted --source . stdout
    sources:
      - ./**

  go-test:
    desc: Run go test
    env:
      # renovate: datasource=docker depName=golang versioning=semver
      GOLANG_IMAGE_VERSION: 1.24.2
      # renovate: datasource=git-refs depName=go lookupName=https://github.com/sagikazarmark/daggerverse currentValue=main
      DAGGER_GO_SHA: e6c14178bcaaff9e102e2a89173ca31479b80629
    cmds:
      - >
        GITHUB_REF= dagger -s call -m github.com/sagikazarmark/daggerverse/go@${DAGGER_GO_SHA}
        --version ${GOLANG_IMAGE_VERSION}
        with-cgo-disabled
        exec --src . --args go --args test --args './...'
        stdout
    sources:
      - ./**/*.go

  ci:
    desc: Run the CI pipeline
    deps:
      - commitlint
      - uncommitted
      - spellcheck
      - lint
      - go-test

  clean:
    desc: Remove autogenerated artifacts
    cmds:
      - rm -rf .task/
